import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Container from '@/components/globals/Container';
import { Footer } from '@/components/globals/Footer';
import Navbar from '@/components/navbar/Navbar';
import NavbarServer from '@/components/navbar/NavbarServer';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased  bg-gray-100`}
			>
				<main className=''>{children}</main>
				<Footer />
			</body>
		</html>
	);
}
